### ISSUE TITLE
InitialMessage is protected and cannot be set

### ISSUE THREAD

**Issue by hooplapunta** [garypretty/botframework#1]
In BestMatchDialog.cs, InitialMessage is set to protected instead of public and cannot be set outside of the class. Not sure how this works as per your LUIS example on your blog: http://www.garypretty.co.uk/2016/08/01/give-your-bot-some-manners-with-the-bestmatchdialog/

**Comment by garypretty** [comment]
I have updated the InitialMessage property to public and committed this change. I will update the Nuget package shortly.
