### ISSUE TITLE
[QnAMakerDialog] Support version 2.0 api

### ISSUE THREAD

**Issue by Robjam** [garypretty/botframework#10]
The [version 2.0](https://westus.dev.cognitive.microsoft.com/docs/services/58994a073d9e04097c7ba6fe/operations/58994a073d9e041ad42d9baa) api documentation has some really nice features I would like to use such as:

- questions that are linked to that answer
- multiple answers

I have a feeling this will not be backwards compatible, but would love to lend a hand if possible.

This is also a partial duplicate of #9

**Comment by garypretty** [comment]
Hi. Sorry for the delay. I will be picking this up this week. I think you are right about backwards compatibility, but I am going to have a think about how best to do this. Will let you know once I have something.

**Comment by Robjam** [comment]
No worries, actually I found out that BotFramework has a [cognitive services](https://github.com/Microsoft/BotBuilder-CognitiveServices) library that appears very similar. While I didn't find it until after I opened this issue, maybe a heads up in the readme might be good?
