### ISSUE TITLE
<bool>

### ISSUE THREAD

**Issue by rickengle** [garypretty/botframework#12]
Hi Gary, super helpful code, I'm using it for a LUIS+QNA dialog.   I noticed when attempting to use this line:
private async Task AfterQnADialog(IDialogContext context, IAwaitable<bool> result)
that it would not accept a type of < bool >.  To get it to work I had to use this with < object > and then cast to bool:

        private async Task AfterQNADialog(IDialogContext context, IAwaitable<object> result)
        {
            var messageHandled = await result;

            bool b_messageHandled = true;
            if (messageHandled is bool)
            {
                b_messageHandled = (bool)messageHandled;

            }           
            if (!b_messageHandled)
            {
                string message = $"Sorry, I did not understand. Type 'help' if you need assistance.";
                await context.PostAsync(message);
            }

            context.Wait(MessageReceived);
        }

Have you seen that issue?

Thanks,
  Rick

**Comment by garypretty** [comment]
Hi.

Great to hear you find this useful. You can change the type of the dialog class for the QnA Dialog in the dialog class itself, which by default specifies object. If you change this you can then change the callback methods await able result type to match.

Does that make sense?

**Comment by rickengle** [comment]
Oh that did work!   I think I tested it in your sample app you published and had an error changing < object > to < bool > but that works just fine.  Thanks very much Gary!
