### ISSUE TITLE
QnA Maker GA release breaks QnaDialog

### ISSUE THREAD

**Issue by jimontheriver** [garypretty/botframework#20]
I created a new knowledge base now that QnA Maker is out of preview and in general availability.

It looks like subscription key is obsolete, now you need to use Endpoint Keys. Also, you provision your own azure service instance, so you need to give it a url to that service, not the westus url.

I'm working on updates now, hopefully I get a PR over tonight.

**Comment by jimontheriver** [comment]
I just created a pull request for this.

**Comment by garypretty** [comment]
@jimontheriver Thanks for this! I have merged your PR. Ill try and update the readme soon and get a new package soon and get a new package on NuGet. On vacation right now, so you saved me a job when I get back 👍
