### ISSUE TITLE
QnaMakerDialog for V4 QnAMaker?

### ISSUE THREAD

**Issue by jay2deguzman** [garypretty/botframework#23]
When will this be compatible to the new version of QnAMaker?

**Comment by garypretty** [comment]
This already is. Latest version on NuGet works with latest QnA.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by PieterHeemeryck** [comment]
It does not seem to be compatible with bot framework V4. All samples in https://github.com/Microsoft/BotBuilder-CognitiveServices/tree/f7f8898d237d5298c3bad30f837d7ec7c0523f21/CSharp/Samples/QnAMaker
refer to a MessagesController and are not in .NET core. Am I missing something, @garypretty ?

**Comment by garypretty** [comment]
There is now a QnaMakerDialog built into the code Microsoft SDK.
