### ISSUE TITLE
How to extract List BestMatch(new string[] { "Hi", "Hi There", "Hello... to a resource File (.resx)

### ISSUE THREAD

**Issue by didaskein** [garypretty/botframework#5]
Hi Gary,

Thank you for your nice projet ! very usefull ;)
Do you have an idea how to get the list of strings ( BestMatch(new string[] { "Hi", "Hi There", "Hello..   )  from multiple resources Files (.resx) (ex FR, US,...) we can imagine having a row : 

BestMatchHelloKeyRow  : Hi|Hi There|Hello|...   in the US.resx file

BestMatchHelloKeyRow  : Bonjour|Salut|...   in the FR.resx file

If you have an idea ;)
Thanks in advance,

**Comment by garypretty** [comment]
Hi. Thanks for your question, this is an interesting scenario.

To support you I have updated the project to support specifying a list of choices using a delimited string so that you can grab it from a resource file. For example,

[BestMatch("bye|bye bye|got to go|see you later|laters|adios", listDelimiter: '|')]
public async Task HandleGoodbye(IDialogContext context, string messageText)
{
    await context.PostAsync("Bye. Looking forward to our next awesome conversation already.");
    context.Wait(MessageReceived);
}

I have pushed the changes into this repo and I will update the NuGet package later today, but it will take a few hours until it is available.

Does that help?

Thanks

Gary

**Comment by didaskein** [comment]
Hi, Thanks Gary,

The issue is that at the compilation time, VS don't know which language to use. I must be dynamic with the user's language.
If i add a Resource.MyKeyItem inside the Attribute, i have a compilation error that you can see below 
![image](https://cloud.githubusercontent.com/assets/13362276/21927917/427ad8e8-d988-11e6-811d-efa1c4278b2f.png)

I think, we need to provide the list for each function in a constructor of GreetingsDialog but i don't know how to to this.

Thx,

**Comment by garypretty** [comment]
Ah ok. I see your issue. I think one option here would be to pass in a locale, e.g. en-GB into the constructor and then you can use this within your dialog to pick the correct resource string for each handler (using the new string param I added). Does that make sense and would that work for you?

**Comment by didaskein** [comment]
I think we can continue to call like that GreetingsDialog : 
![image](https://cloud.githubusercontent.com/assets/13362276/21928814/44e20520-d98d-11e6-97e2-79ab890f7b89.png)

The locale is defined for the Thread Before calling GreetingsDialog :
![image](https://cloud.githubusercontent.com/assets/13362276/21928862/83da0aa2-d98d-11e6-96bf-43c645c14bbf.png)

Then in the contructor of GreetingsDialog we need to linked the string inside resource file for Hello with | separator to the function. 
![image](https://cloud.githubusercontent.com/assets/13362276/21928908/d8b3fd30-d98d-11e6-9666-1a7309818926.png)

But how to link the function to the Match list no idea... :(

**Comment by didaskein** [comment]
Hi Gary,

It is working perfectly ! :) Thank you

![image](https://cloud.githubusercontent.com/assets/13362276/22144336/a5c8efc8-defd-11e6-965d-fec10f6a1fb6.png)

![image](https://cloud.githubusercontent.com/assets/13362276/22144368/c218cbe4-defd-11e6-8869-7138b7bdcc24.png)

And a little helper to add Random in the answers ;)
![image](https://cloud.githubusercontent.com/assets/13362276/22144377/cfd9dff2-defd-11e6-9e38-cc67d971eaf9.png)

![image](https://cloud.githubusercontent.com/assets/13362276/22144391/db27cb26-defd-11e6-90f3-af71fd860082.png)

++

**Comment by garypretty** [comment]
That's fantastic news. So glad you found it useful. Good luck with your bot building. FYI I have added a new dialog to the repo and NuGet. QnAMakerDialog - check my blog post out at www.garypretty.co.uk and hopefully it might be useful.
